### ISSUE TITLE
Potential error in the schematic 

### ISSUE THREAD

**Issue by tymcneer** [nothinglabs/openmelt2#1]
The Motor 1 tag has wire tag of 9 and a microcontroller pin designation of 4. I believe the microcontroller pin is supposed to be pin 9 for Motor 1 and pin 10 for Motor 2 ( I can't confirm pin 10 for Motor 2, as I built the single wheel test platform)

**Comment by nothinglabs** [comment]
Yup - that was definitely wrong.  Good catch.

Just checked in a correction.  Thanks for letting me know!

Does your test platform work? I haven't heard back from anyone who has
tried building the new version - you might be the first!

-Rich

**Comment by tymcneer** [comment]
Thanks for confirming! I was not entirely sure the problem wasn't on my end.
 
As to functionality, yes, it functions. There is an issue where I need to adjust the vector of translation, in relation to the heading light, but that seems to be a simple software fix. The current plan is to create a new test chassis, with mounts for the other components, and then try it at the March Maryland Area Combat Robotics Organization (MACRO) competition. I will have more information by April.
 
Ty

**Comment by nothinglabs** [comment]
great to hear you got it working!  

To adjust the heading LED offset - just tweak DEFAULT_LED_OFFSET_PERCENT in melty_config.h (or use the interactive setup).

If you've used the interactive setup - but want the settings in melty_config.h to over-ride - just change EEPROM_WRITTEN_SENTINEL_VALUE to a new value.

Side note - I just figured out that an 11.1v fully-charged LiPo battery (12.6v) is a bit too much for the Adafruit ItsyBitsy v-reg (probably same for Arduino Micro).  It usually works - but definitely can cause issues.  I just updated the docs to suggest a dedicate voltage regulator for over 7.4v.

Feel free to reach out directly with any questions to rich@nothinglabs.com.

Good luck with the competition!

-Rich

**Comment by tymcneer** [comment]
Glad to know you had experimented with higher voltages, and warned others that there could be an issue with the regulator.
 
Once I get some time, hopefully this week, I am going to get the test bed working correctly and then move on to a revised chassis. Once that is complete, testing will resume on Monday.
 
Ty
